In [30]:
# Import Libraries
import pandas as pd

In [31]:
# Read Data
data = pd.read_csv("hr_analytics.csv")
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [32]:
data.describe()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,0.612834,0.716102,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268
std,0.248631,0.171169,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,0.440000,0.560000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000
50%,0.640000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,0.820000,0.870000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64
 3   average_montly_hours   14999 non-null  int64
 4   time_spend_company     14999 non-null  int64
 5   Work_accident          14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotion_last_5years  14999 non-null  int64
 8   sales                  14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [34]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
data.sales=encoder.fit_transform(data.sales)
data.salary=encoder.fit_transform(data.salary)

In [35]:
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,7,1
1,0.80,0.86,5,262,6,0,1,0,7,2
2,0.11,0.88,7,272,4,0,1,0,7,2
3,0.72,0.87,5,223,5,0,1,0,7,1
4,0.37,0.52,2,159,3,0,1,0,7,1

In [36]:
y=data.left
X=data.drop(['left'],axis=1)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y , test_size = 0.2, random_state=1)

In [9]:
# Using Linear Model and select Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(C=10,solver='liblinear')
#model = LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression(C=10, solver='liblinear')

In [10]:
model.score(X_test,Y_test)

0.7693333333333333

In [11]:
# Do Model prediction on test data
prediction = model.predict(X_test)

In [12]:
prediction

array([0, 0, 0, ..., 0, 1, 0])

In [13]:
probabilities = model.predict_proba(X_test)

In [14]:
probabilities

array([[0.58306857, 0.41693143],
       [0.63815746, 0.36184254],
       [0.82078278, 0.17921722],
       ...,
       [0.86700861, 0.13299139],
       [0.4045668 , 0.5954332 ],
       [0.81380324, 0.18619676]])

In [15]:
# Use metrics to do accuracy score and understand the model accuracy
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(prediction,Y_test)

0.7693333333333333

In [16]:
print(confusion_matrix(Y_test,prediction))

[[2114  173]
 [ 519  194]]

In [17]:
from sklearn.svm import SVC
svcmodel=SVC(C=100)
svcmodel.fit(X_train,Y_train)
print(svcmodel.score(X_test,Y_test))

0.8946666666666667

In [18]:
# Do Model prediction on test data
svc_prediction = svcmodel.predict(X_test)

In [19]:
print(confusion_matrix(Y_test,svc_prediction))

[[2177  110]
 [ 206  507]]

In [20]:
#training and testing are done on entirely different machines
#training data need to be exported as pickle file and imported into test/inference machine
#inference machine need not be huge machine like training and this does the model prediction.

import pickle

In [21]:
#creating sample pickle file
file = open('model_1_apr.pkl','wb')

In [22]:
pickle.dump(model,file)

In [23]:
file.close()
#this is end of training machine activity

In [24]:
#This is start of test/inference machine activity

file = open('model_1_apr.pkl','rb')
mylogitmodel = pickle.load(file)

In [25]:
mylogitmodel.score(X_test,Y_test)

0.7693333333333333

In [26]:
prediction = mylogitmodel.predict(X_test)

In [27]:
prediction

array([0, 0, 0, ..., 0, 1, 0])

In [28]:
probas = mylogitmodel.predict_proba(X_test)

In [29]:
probas

array([[0.58306857, 0.41693143],
       [0.63815746, 0.36184254],
       [0.82078278, 0.17921722],
       ...,
       [0.86700861, 0.13299139],
       [0.4045668 , 0.5954332 ],
       [0.81380324, 0.18619676]])